### ISSUE TITLE
Database Models

### ISSUE THREAD

**Issue by jarrywc** [jarrywc/you-note#11]
Need to setup models.py for PostgreSQL

**Comment by jarrywc** [comment]
User
Id
Email
Password

Movies
Id
User_Id
Ext_Movie_Source
Title

Note_Line
Id
Movie_Id
Sort_Id
Content

**Comment by OchreVale** [comment]
Thanks Jarred

**Comment by jarrywc** [comment]
I realized we should call it video not movie

**Comment by OchreVale** [comment]
Yes I wrote video in my notes. All good

**Comment by OchreVale** [comment]
What does sort_id refer to?
